// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecordPoint.Connectors.SDK.Databases.PostgreSql;

#nullable disable

namespace RecordPoint.Connectors.SDK.Databases.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSqlConnectorDbContext))]
    [Migration("20251014032105_ConnectorConfigUpdate")]
    partial class ConnectorConfigUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecordPoint.Connectors.SDK.Connectors.ConnectorConfigurationModel", b =>
                {
                    b.Property<string>("ConnectorId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ChannelDiscoveryEnqueuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ChannelDiscoveryExecutedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectorTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConnectorId");

                    b.ToTable("Connectors");
                });

            modelBuilder.Entity("RecordPoint.Connectors.SDK.Content.AggregationModel", b =>
                {
                    b.Property<string>("ConnectorId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<string>("ParentExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ConnectorId", "ExternalId");

                    b.ToTable("Aggregations");
                });

            modelBuilder.Entity("RecordPoint.Connectors.SDK.Content.ChannelModel", b =>
                {
                    b.Property<string>("ConnectorId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("ConnectorId", "ExternalId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("RecordPoint.Connectors.SDK.Work.ManagedWorkStatusModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastStatusUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ManagedWorkStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
