using Microsoft.Extensions.Logging;
using RecordPoint.Connectors.SDK.Diagnostics;
using System;

namespace RecordPoint.Connectors.SDK.R365
{

    /// <summary>
    /// Adapter that converts log messages generated by the SDK
    /// </summary>
    public class SDKLogAdapter : ILog
    {

        private readonly ILogger _logger;

        /// <summary>
        /// Instantiates a new SDKLogAdapter
        /// </summary>
        /// <param name="logger"></param>
        public SDKLogAdapter(ILogger<SDKLogAdapter> logger)
        {
            _logger = logger;
        }

        public void LogCritical(Type callerType, string methodName, Exception ex, string message = null)
        {
            _logger.LogCritical(ex, $"Connector SDK error CallerType[{callerType}] Method:[{methodName}] Message:[{message}]");
        }

        public void LogError(Type callerType, string methodName, Exception ex, string message = null)
        {
            _logger.LogError(ex, $"Error::Type:[{callerType}] Method:[{methodName}] Message:[{message}]");
        }

        public void LogMessage(Type callerType, string methodName, string message, long? elapsedTimeTicks = null)
        {
            _logger.LogInformation($"Information::Type:[{callerType}] Method:[{methodName}] Message:[{message}] ExecutedTime:[{elapsedTimeTicks ?? -1}]");
        }

        public void LogVerbose(Type callerType, string methodName, string message, long? elapsedTimeTicks = null)
        {
            _logger.LogTrace($"Verbose::Type:[{callerType}] Method:[{methodName}] Message:[{message}] ExecutedTime:[{ elapsedTimeTicks ?? -1}]");
        }

        public void LogWarning(Type callerType, string methodName, string message, long? elapsedTimeTicks = null)
        {
            _logger.LogWarning($"Warning::Type:[{callerType}] Method:[{methodName}] Message:[{message}] ExecutedTime:[{ elapsedTimeTicks ?? -1}]");
        }
    }

}
